id: Stamus Networks - Get Extra Data
version: -1
name: Stamus Networks - Get Extra Data
description: Get Extra Information from a Declaration of Compromise
fromversion: "6.8.0"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2748770b-db10-492a-8d38-5c7973bade90
    type: start
    task:
      id: 2748770b-db10-492a-8d38-5c7973bade90
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: af372da4-9b8f-4cf0-8e48-f4cfca8eedb1
    type: regular
    task:
      id: af372da4-9b8f-4cf0-8e48-f4cfca8eedb1
      version: -1
      name: Get Event
      description: '[Get base events including protocol metadata that can be used as IOCs.]'
      script: '|||stamus-get-events'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      id:
        simple: ${incident.stamusid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: ad2be62a-9ca9-4bed-857c-ef05560502ee
    type: regular
    task:
      id: ad2be62a-9ca9-4bed-857c-ef05560502ee
      version: -1
      name: Get Host Information
      description: '[Get host-id informations]'
      script: '|||stamus-get-host-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      ip:
        simple: ${incident.stamustarget}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 1f1dbec6-3073-4e54-87b4-b8981fa4a6b6
    type: regular
    task:
      id: 1f1dbec6-3073-4e54-87b4-b8981fa4a6b6
      version: -1
      name: Get By IOC (event by source ip)
      description: '[Get events with IOC key/value filter]'
      script: '|||stamus-get-by-ioc'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      key:
        simple: src_ip
      value:
        simple: ${BaseIntegration.Output.[0].src_ip}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 12c9eb19-e96b-47f6-8b4f-47232395acfb
    type: regular
    task:
      id: 12c9eb19-e96b-47f6-8b4f-47232395acfb
      version: -1
      name: Quarantine EDR
      description: '[Trigger Quarantine on EDR]'
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 3e883fee-f4e5-4c0d-8b79-0b0385109651
    type: regular
    task:
      id: 3e883fee-f4e5-4c0d-8b79-0b0385109651
      version: -1
      name: Enevent to SIEM
      description: '[Send event to SIEM]'
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 8e53acab-c40b-4d0d-862d-f06e4ec62bfc
    type: title
    task:
      id: 8e53acab-c40b-4d0d-862d-f06e4ec62bfc
      version: -1
      name: get event details
      type: title
      iscommand: false
      brand: ""
      description: '[Get Metadata associated to event]'
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 51e46a4c-ff68-4883-8251-1676f59ec87a
    type: title
    task:
      id: 51e46a4c-ff68-4883-8251-1676f59ec87a
      version: -1
      name: Get Host Details
      type: title
      iscommand: false
      brand: ""
      description: '[Get information about asset from Host Insight]'
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
tests:
- No tests (auto formatted)
